# Generated by Django 3.1.7 on 2021-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210310_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=80),
        ),
    ]
