# Generated by Django 3.1.7 on 2021-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210312_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default='Article-47954', max_length=80),
        ),
    ]
